// Generated by processRepos.py on 2023-01-27 10:18:51

export default [
  {
    "name": "ANTIGRAV-BOOTS",
    "description": "Combine *.csv files from your Windows Explorer context menu",
    "url": "https://github.com/scgrn/ANTIGRAV-BOOTS",
    "language": "Java",
    "color": "#b07219",
    "forks": 0,
    "stars": 0
  },
  {
    "name": "DerivativeDungeon",
    "description": "A terminal-based roguelike RPG-ish dungeon crawler thing",
    "url": "https://github.com/scgrn/DerivativeDungeon",
    "language": "Lua",
    "color": "#000080",
    "forks": 0,
    "stars": 0
  },
  {
    "name": "Mustard-SampleProject",
    "description": "Mustard engine Win64 debug runtime with sample game",
    "url": "https://github.com/scgrn/Mustard-SampleProject",
    "language": "Lua",
    "color": "#000080",
    "forks": 0,
    "stars": 1
  },
  {
    "name": "Project-Euler",
    "description": "Solutions for the first 100 Project Euler problems (WIP)",
    "url": "https://github.com/scgrn/Project-Euler",
    "language": "C++",
    "color": "#f34b7d",
    "forks": 0,
    "stars": 0
  },
  {
    "name": "Sangwidge",
    "description": "A Google Chrome extension that replaces every instance of \"sandwich\" with \"sangwidge\"",
    "url": "https://github.com/scgrn/Sangwidge",
    "language": "JavaScript",
    "color": "#f1e05a",
    "forks": 0,
    "stars": 0
  },
  {
    "name": "scgrn.github.io",
    "description": "Portfolio website",
    "url": "https://github.com/scgrn/scgrn.github.io",
    "language": "HTML",
    "color": "#e34c26",
    "forks": 0,
    "stars": 0
  },
  {
    "name": "sendMail",
    "description": "A utility to send email via Outlook from the Windows command line",
    "url": "https://github.com/scgrn/sendMail",
    "language": "Python",
    "color": "#3572A5",
    "forks": 0,
    "stars": 0
  }
]